// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRedkjDwAuGzfrh0Rdmxqcukp06MYu2qA',
    appId: '1:514294949355:web:bb6141c8bcfb1524c1a5ae',
    messagingSenderId: '514294949355',
    projectId: 'rebuildapp-f8417',
    authDomain: 'rebuildapp-f8417.firebaseapp.com',
    storageBucket: 'rebuildapp-f8417.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASIz5GyawD1BdW8s68keGPi2lKFjmsjrE',
    appId: '1:514294949355:android:5c780ea08eca4a38c1a5ae',
    messagingSenderId: '514294949355',
    projectId: 'rebuildapp-f8417',
    storageBucket: 'rebuildapp-f8417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-RZJPz8O0KcXGV94YzGhGx28ofD7i50',
    appId: '1:514294949355:ios:883fa5cf49374080c1a5ae',
    messagingSenderId: '514294949355',
    projectId: 'rebuildapp-f8417',
    storageBucket: 'rebuildapp-f8417.firebasestorage.app',
    iosBundleId: 'com.example.rebuildFlat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRedkjDwAuGzfrh0Rdmxqcukp06MYu2qA',
    appId: '1:514294949355:web:70d021b8253180f6c1a5ae',
    messagingSenderId: '514294949355',
    projectId: 'rebuildapp-f8417',
    authDomain: 'rebuildapp-f8417.firebaseapp.com',
    storageBucket: 'rebuildapp-f8417.firebasestorage.app',
  );
}
